### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by dnichk** [javaguirre/comment#31]
[Enter steps to reproduce below:]

1. Have a bash script open.
2. GO to : > packages > COmments > toggle

**Atom Version**: 1.9.6
**System**: Mac OS X 10.11.6
**Thrown From**: [comment](https://github.com/havber/comment) package, v0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/dustin/.atom/packages/comment/lib/comment.js:173

TypeError: Cannot read property 'length' of undefined
    at supportsMultiline (/Users/dustin/.atom/packages/comment/lib/comment.js:173:41)
    at atom-workspace.module.exports.toggle (/Users/dustin/.atom/packages/comment/lib/comment.js:34:17)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1104:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

### Commands

```
     -0:17.1.0 core:close (div.pane-item.native-key-bindings.about)
     -0:16.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.use-animations.theme-atom-material-syntax-dark.theme-atom-material-ui.has-custom-icons)
     -0:00.1.0 comment:toggle (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode-delete, v0.6.1 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (active)
atom-material-ui, v1.3.3 (active)
atom-ternjs, v0.14.2 (active)
atomic-chrome, v0.3.0 (active)
auto-detect-indentation, v1.1.0 (active)
auto-update-packages, v1.0.1 (active)
autoclose-html, v0.23.0 (active)
autocomplete-modules, v1.6.1 (active)
autocomplete-paths, v1.0.2 (active)
comment, v0.3.0 (inactive)
docblockr, v0.7.4 (active)
editorconfig, v1.4.1 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.18 (active)
fold-functions, v0.4.3 (active)
foldingtext-for-atom, v0.9.2 (active)
git-plus, v5.16.2 (inactive)
glowing-cursor, v0.1.1 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
language-applescript, v0.2.2 (inactive)
language-babel, v2.32.2 (active)
language-docker, v1.1.6 (active)
language-graphql, v0.2.0 (active)
language-markdown, v0.16.1 (active)
linter, v1.11.15 (active)
linter-docker, v0.1.2 (active)
linter-eslint, v7.2.4 (active)
linter-python, v3.0.5 (active)
markdown-folder, v0.5.0 (inactive)
markdown-format, v2.5.1 (active)
markdown-pdf, v1.5.0 (inactive)
markdown-preview-plus, v2.4.0 (active)
markdown-themeable-pdf, v1.2.0 (active)
markdown-toc, v0.4.1 (inactive)
markdown-writer, v2.5.1 (inactive)
minimap, v4.24.7 (active)
minimap-pigments, v0.2.1 (active)
open-recent, v5.0.0 (active)
pigments, v0.31.2 (active)
preview, v0.16.9 (inactive)
set-syntax, v0.3.0 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
solarized-dark-ui, v0.3.1 (inactive)
sort-lines, v0.14.0 (inactive)
sync-settings, v0.7.2 (active)
synced-sidebar, v0.4.3 (active)
term3, v0.22.1 (active)
todo-show, v1.7.0 (inactive)
toggle-quotes, v1.0.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.3 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

Any idea? Anythign to do with the language of the code I'm working on?

**Comment by javaguirre** [comment]
Thank you! This should be fixed on a5393529b0dbd676b1e85b1d40dbc0b922452911

Please let me know if the problem persists. :-)
