### ISSUE TITLE
Uncaught ReferenceError: toggleComments is not defined

### ISSUE THREAD

**Issue by kemalelmizan** [javaguirre/comment#35]
Error happened after installing and pressing the key combination for toggleComments (Command+shift+m)
anybody have the same issue?

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [comment](https://github.com/havber/comment) package, v0.5.0
### Stack Trace

Uncaught ReferenceError: toggleComments is not defined

```
At /Users/mac/.atom/packages/comment/lib/comment-utils.js:50

ReferenceError: toggleComments is not defined
    at Object.module.exports.toggleHtmlSingleLineOrEmptySelection (/Users/mac/.atom/packages/comment/lib/comment-utils.js:50:44)
    at Object.module.exports.toggleSingleCommentsWithRange (/Users/mac/.atom/packages/comment/lib/comment-utils.js:33:18)
    at Object.module.exports.toggle (/Users/mac/.atom/packages/comment/lib/comment-utils.js:13:18)
    at atom-workspace.module.exports.toggle (/Users/mac/.atom/packages/comment/lib/comment.js:31:15)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:12.9.0 comment:toggle (atom-text-editor.editor.is-focused)
     -1:10.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:09.9.0 core:select-down (atom-text-editor.editor.is-focused)
     -1:08.6.0 comment:toggleSingleLine (atom-text-editor.editor.is-focused)
     -1:07.4.0 comment:toggle (atom-text-editor.editor.is-focused)
  2x -1:04.5.0 core:undo (atom-text-editor.editor.is-focused)
     -1:01.8.0 comment:toggle (atom-text-editor.editor.is-focused)
  2x -0:59.5.0 core:undo (atom-text-editor.editor.is-focused)
  2x -0:55.3.0 comment:toggle (atom-text-editor.editor.is-focused)
     -0:47.1.0 comment:toggleSingleLine (atom-text-editor.editor.is-focused)
     -0:44.7.0 comment:toggle (atom-text-editor.editor.is-focused)
     -0:43.5.0 comment:toggleSingleLine (atom-text-editor.editor.is-focused)
     -0:41.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:41.2.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:40.1.0 comment:toggleSingleLine (atom-text-editor.editor.is-focused)
     -0:00.0 comment:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "comment": {}
}
```
### Installed Packages

``` coffee
# User
comment, v0.5.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jeremyhatfield** [comment]
Yes. I'm having the same issue.

1. I installed the package from within the Atom package manager.
2. Restarted Atom (just in case.)
3. Selected line and hit shift-cmd-m.
4. Error occurs every time.

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [comment](https://github.com/havber/comment) package, v0.5.0


### Stack Trace

Uncaught ReferenceError: toggleComments is not defined

```
At /Users/jeremy/.atom/packages/comment/lib/comment-utils.js:50

ReferenceError: toggleComments is not defined
    at Object.module.exports.toggleHtmlSingleLineOrEmptySelection (/Users/jeremy/.atom/packages/comment/lib/comment-utils.js:50:44)
    at Object.module.exports.toggleSingleCommentsWithRange (/Users/jeremy/.atom/packages/comment/lib/comment-utils.js:33:18)
    at Object.module.exports.toggle (/Users/jeremy/.atom/packages/comment/lib/comment-utils.js:13:18)
    at atom-workspace.module.exports.toggle (/Users/jeremy/.atom/packages/comment/lib/comment.js:31:15)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -4:53.4.0 comment:toggle (atom-text-editor.editor.is-focused)
  2x -2:19.5.0 comment:toggleSingleLine (atom-text-editor.editor.is-focused)
     -2:14 bracket-matcher:select-inside-brackets (atom-text-editor.editor.is-focused)
  3x -2:11.4.0 core:undo (atom-text-editor.editor.is-focused)
  3x -1:59.9.0 core:redo (atom-text-editor.editor.is-focused)
  2x -1:51.9.0 comment:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (inactive)
comment, v0.5.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Eblonko** [comment]
same


**Atom Version**: 1.8.0
**System**: Ubuntu 16.04.1
**Thrown From**: [comment](https://github.com/havber/comment) package, v0.5.0


### Stack Trace

Uncaught ReferenceError: toggleComments is not defined

```
At /home/vitaly/.atom/packages/comment/lib/comment-utils.js:50

ReferenceError: toggleComments is not defined
    at Object.module.exports.toggleHtmlSingleLineOrEmptySelection (/home/vitaly/.atom/packages/comment/lib/comment-utils.js:50:44)
    at Object.module.exports.toggleSingleCommentsWithRange (/home/vitaly/.atom/packages/comment/lib/comment-utils.js:33:18)
    at Object.module.exports.toggle (/home/vitaly/.atom/packages/comment/lib/comment-utils.js:13:18)
    at atom-workspace.module.exports.toggle (/home/vitaly/.atom/packages/comment/lib/comment.js:31:15)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:06.3.0 editor:indent (atom-text-editor.editor.is-focused)
  3x -1:06.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:05.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:05.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:05.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:03.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:03.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:01.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:51.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:49.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:48 core:save (atom-text-editor.editor.is-focused)
     -0:33.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:33.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:21 core:copy (atom-text-editor.editor.is-focused)
     -0:15.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.1.0 comment:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "atom-terminal-panel",
      "linter-python",
      "linter-jshint",
      "linter-jscs"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-minify"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.0.2
atom-jade, v0.3.0
atom-minify, v0.7.5
atomic-chrome, v0.3.0
comment, v0.5.0
git-plus, v5.18.0
gtk-dark-theme, v0.1.4
language-pascal, v0.18.1
linter, v1.11.18
linter-eslint, v7.3.2
linter-flake8, v1.13.4
node-snippets, v0.0.7
python-indent, v1.0.0

# Dev
No dev packages
```

**Comment by javaguirre** [comment]
Hi! sorry for the very late response, I'll check it out :-)

**Comment by javaguirre** [comment]
Thank you for reporting, this is now fixed on v.0.6.0
