### ISSUE TITLE
Failed to activate the comment package

### ISSUE THREAD

**Issue by Klustre** [javaguirre/comment#36]
[Enter steps to reproduce below:]
1. Installed comment-master from this repo into '/Users/User/.atom/packages'
2. Used the shortcut of comment

**Atom Version**: 1.12.0-beta1
**Electron Version**: 1.3.6
**System**: Mac OS X 10.10.5
**Thrown From**: [comment](https://github.com/havber/comment) package, v0.5.0
### Stack Trace

Failed to activate the comment package

```
At Cannot find module 'sprint'

Error: Cannot find module 'sprint'
    at Module._resolveFilename (module.js:440:15)
    at Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:388:25)
    at Object.<anonymous> (/Users/Remco/.atom/packages/comment-master/lib/comment.js:2:31)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:741:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:174:16)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:821:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:240:20)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:584:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:392:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```
### Commands

```
     -0:00.0 comment:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "minimap",
      "file-types",
      "linter",
      "linter-jshint",
      "comment",
      "comment",
      "comment",
      "comment",
      "comment",
      "comment",
      "comment",
      "comment"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/Remco/Projects/Dev",
    "telemetryConsent": "no",
    "themes": [
      "spacegray-dark-ui",
      "spacegray-atom-dark-syntax"
    ],
    "useCustomTitleBar": true
  }
}
```
### Installed Packages

``` coffee
# User
api-docs, v0.0.6 (active)
atom-beautify, v0.29.13 (inactive)
atom-monokai-soda, v2.0.0 (inactive)
base16-ocean-dark-spacegray, v0.12.0 (inactive)
build, v0.65.0 (active)
busy, v0.7.0 (active)
change-case, v0.6.3 (active)
comment, v0.5.0 (inactive)
default-language, v0.3.0 (active)
docblockr, v0.8.7 (active)
eval-javascript, v1.2.0 (inactive)
file-icons, v1.7.22 (active)
file-types, v0.5.4-p1 (inactive)
git-plus, v5.18.0 (active)
git-status, v0.3.4 (inactive)
jshint, v1.8.6 (active)
linter, v1.11.18 (inactive)
linter-jshint, v3.0.0 (inactive)
minimap, v4.25.0 (inactive)
open-on-bitbucket, v0.4.0 (inactive)
spacegray-atom-dark-syntax, v1.2.0 (active)
spacegray-atom-dark-ui, v1.0.0 (inactive)
spacegray-dark-neue-syntax, v1.3.0 (inactive)
spacegray-dark-syntax, v0.2.0 (inactive)
spacegray-dark-ui, v0.12.0 (active)
split-diff, v1.0.5 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.0 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.3 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.102.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by javaguirre** [comment]
Hi! Sorry for the late response, i'll try to replicate the issue.

Thanks for reporting!

**Comment by javaguirre** [comment]
Hi! If you install it manually, you need to manually run `npm install` in the root of the plugin.

So if you clone this and add it to your github plugin root, you'll need to npm install inside the comment plugin directory.
