### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by waheedi** [javaguirre/comment#37]
While just hitting shift+cmd+m

TypeError: Cannot read property 'length' of undefined
    at Object.isSingleLineCommented (/Users/Waheed/.atom/packages/comment/lib/comment-utils.js:220:44)
    at Object.processSingleLineComment (/Users/Waheed/.atom/packages/comment/lib/comment-utils.js:101:18)
    at Object.toggleCommentsForSingleLine (/Users/Waheed/.atom/packages/comment/lib/comment-utils.js:75:29)
    at Object.toggleSingleCommentsWithRange (/Users/Waheed/.atom/packages/comment/lib/comment-utils.js:35:18)
    at Object.toggle (/Users/Waheed/.atom/packages/comment/lib/comment-utils.js:13:18)
    at atom-workspace.toggle (/Users/Waheed/.atom/packages/comment/lib/comment.js:31:15)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)

**Comment by javaguirre** [comment]
Hi! Let me check if i can reproduce it. Thanks for reporting!

**Comment by javaguirre** [comment]
Fixed on v0.6.1, thank you!
