### ISSUE TITLE
Uncaught ReferenceError: toggleComments is not defined

### ISSUE THREAD

**Issue by afridikhalid** [javaguirre/comment#40]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [comment](https://github.com/havber/comment) package 0.5.0

### Stack Trace

Uncaught ReferenceError: toggleComments is not defined

```
At /Users/khalidafridi/.atom/packages/comment/lib/comment-utils.js:50

ReferenceError: toggleComments is not defined
    at Object.toggleHtmlSingleLineOrEmptySelection (/packages/comment/lib/comment-utils.js:50:44)
    at Object.toggleSingleCommentsWithRange (/packages/comment/lib/comment-utils.js:33:18)
    at Object.toggle (/packages/comment/lib/comment-utils.js:13:18)
    at /packages/comment/lib/comment.js:31:15)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1164:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -2:19.8.0 application:new-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:14.7.0 editor:newline (input.hidden-input)
     -2:14.1.0 core:backspace (input.hidden-input)
     -2:11.8.0 core:save (input.hidden-input)
     -2:02.6.0 core:backspace (input.hidden-input)
     -1:53 tree-view:remove (span.name.icon.icon-file-text)
     -1:38.1.0 application:new-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:35.6.0 core:save (input.hidden-input)
     -0:14.1.0 comment:toggle (input.hidden-input)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-clock 0.1.3 
atom-material-syntax 1.0.2 
comment 0.5.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
linter-write-good 0.8.0 
qolor 0.4.1 
```

**Comment by javaguirre** [comment]
This is duped, #35
