### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by gaevoc** [javaguirre/comment#42]
[Enter steps to reproduce:]

1. Select one line, including newline
2. Goto Packages->Comment->Toggle

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [comment](https://github.com/havber/comment) package 0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\gvocca.HIRTEC\.atom\packages\comment\lib\comment-utils.js:220

TypeError: Cannot read property 'length' of undefined
    at Object.isSingleLineCommented (/packages/comment/lib/comment-utils.js:220:44)
    at Object.processSingleLineComment (/packages/comment/lib/comment-utils.js:101:18)
    at /packages/comment/lib/comment-utils.js:91:38)
    at Array.forEach (native)
    at Object.toggleCommentsForUnsupportedMultiline (/packages/comment/lib/comment-utils.js:89:15)
    at Object.toggleMultilineCommentsWithRange (/packages/comment/lib/comment-utils.js:21:33)
    at Object.toggle (/packages/comment/lib/comment-utils.js:11:18)
    at /packages/comment/lib/comment.js:31:15)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1164:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:35.6.0 markdown-preview:toggle (input.hidden-input)
     -0:33.9.0 core:select-down (input.hidden-input)
     -0:32.1.0 markdown-preview:toggle (input.hidden-input)
     -0:17.5.0 comment:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-runner 2.7.1 
close-on-left 0.7.2 
comment 0.5.0 
split-diff 1.2.0 
sync-settings 0.8.1 
todo-show 1.11.0 
```

**Comment by javaguirre** [comment]
Fixed on v0.6.1, thank you!
