### ISSUE TITLE
Uncaught ReferenceError: toggleComments is not defined

### ISSUE THREAD

**Issue by liao1994** [javaguirre/comment#43]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [comment](https://github.com/havber/comment) package 0.5.0

### Stack Trace

Uncaught ReferenceError: toggleComments is not defined

```
At C:\Users\liao\.atom\packages\comment\lib\comment-utils.js:50

ReferenceError: toggleComments is not defined
    at Object.toggleHtmlSingleLineOrEmptySelection (/packages/comment/lib/comment-utils.js:50:44)
    at Object.toggleSingleCommentsWithRange (/packages/comment/lib/comment-utils.js:33:18)
    at Object.toggle (/packages/comment/lib/comment-utils.js:13:18)
    at /packages/comment/lib/comment.js:31:15)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:41.9.0 core:move-left (input.hidden-input)
     -0:41.7.0 core:move-down (input.hidden-input)
     -0:41.5.0 core:move-left (input.hidden-input)
     -0:41.4.0 core:move-up (input.hidden-input)
 16x -0:41.2.0 core:move-left (input.hidden-input)
     -0:39.4.0 core:select-down (input.hidden-input)
     -0:35.8.0 core:undo (input.hidden-input)
     -0:34.8.0 bracket-matcher:go-to-matching-bracket (input.hidden-input)
     -0:33.8.0 core:move-down (input.hidden-input)
  2x -0:33.5.0 core:move-up (input.hidden-input)
     -0:33.1.0 core:select-down (input.hidden-input)
     -0:32.9.0 core:select-left (input.hidden-input)
     -0:32.5.0 core:select-down (input.hidden-input)
     -0:30.5.0 bracket-matcher:go-to-matching-bracket (input.hidden-input)
     -0:28.9.0 core:undo (input.hidden-input)
  2x -0:23.7.0 comment:toggle (span.syntax--punctuation.syntax--definition.syntax--string.syntax--begin.syntax--html)
```

### Non-Core Packages

```
atom-alignment 0.12.1 
atom-beautify 0.29.17 
atom-html-templates 0.1.3 
autocomplete-json 5.2.0 
autocomplete-paths 1.0.5 
autocomplete-xml 0.9.4 
color-picker 2.2.5 
comment 0.5.0 
css-snippets 1.1.0 
csscomb 0.3.1 
emmet 2.4.3 
file-icons 2.0.15 
git-plus 7.2.2 
highlight-selected 0.12.0 
minimap 4.26.8 
php-integrator-autocomplete-plus 1.2.0 
run-in-browser 0.1.3 
```

**Comment by javaguirre** [comment]
Fixed on v0.6.0, thanks for reporting!
