### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by arminmon** [javaguirre/comment#44]
commenting doesn't work for pug.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [comment](https://github.com/havber/comment) package 0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/arminmon/.atom/packages/comment/lib/comment-utils.js:220

TypeError: Cannot read property 'length' of undefined
    at Object.isSingleLineCommented (/packages/comment/lib/comment-utils.js:220:44)
    at Object.processSingleLineComment (/packages/comment/lib/comment-utils.js:101:18)
    at Object.toggleCommentsForSingleLine (/packages/comment/lib/comment-utils.js:75:29)
    at Object.toggleSingleCommentsWithRange (/packages/comment/lib/comment-utils.js:35:18)
    at Object.toggle (/packages/comment/lib/comment-utils.js:13:18)
    at /packages/comment/lib/comment.js:31:15)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -9:28.2.0 core:copy (input.hidden-input)
     -9:26.7.0 core:backspace (input.hidden-input)
     -9:24.3.0 editor:outdent-selected-rows (input.hidden-input)
     -8:15.7.0 editor:consolidate-selections (input.hidden-input)
     -8:15.7.0 core:cancel (input.hidden-input)
  5x -8:14.3.0 core:save (input.hidden-input)
     -0:50.9.0 settings-view:open (input.hidden-input)
     -0:46.6.0 core:confirm (input.hidden-input)
     -0:06.2.0 comment:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-css-comb 3.1.0 
atom-electron-snippets 2.0.3 
atom-jade 0.3.0 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-react-native-autocomplete 0.0.27 
atom-snazzy-clear-syntax 0.5.3 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-json 5.3.0 
busy-signal 1.3.0 
color-picker 2.2.5 
comment 0.5.0 
copy-as-rtf 0.9.3 
copy-paste 0.6.0 
css-declaration-sorter 0.4.0 
cucumber 0.6.0 
cucumber-step 0.2.0 
export-html 3.1.0 
expose 0.14.0 
file-icons 2.0.17 
git-plus 7.3.3 
git-projects 1.17.0 
git-time-machine 1.5.6 
highlight-line 0.12.0 
highlight-selected 0.12.0 
html2haml 0.10.0 
indent-guide-improved 1.4.12 
intentions 1.1.2 
jade-beautify 0.1.5 
jquery-snippets 11.0.0 
js2coffee 0.19.1 
language-asp 1.0.0 
language-aspx 0.5.0 
language-babel 2.56.2 
language-cjsx 0.3.0 
language-cucumber 0.0.1 
language-haml 0.24.1 
language-javascript-jsx 0.3.7 
language-pug 0.0.21 
language-rspec 0.6.1 
language-srt 0.1.1 
linter 2.1.0 
linter-coffeelint 1.2.1 
linter-haml 2.0.0 
linter-pug-lint 0.2.0 
linter-rubocop 1.1.0 
linter-ruby 1.2.5 
linter-scss-lint 3.1.0 
linter-ui-default 1.1.0 
markdown-preview-plus 2.4.9 
marvel-monokai 0.1.0 
minimap 4.26.8 
nuclide undefined 
pigments 0.39.0 
pristine-ui 1.0.15 
qolor 0.4.1 
resize-indent 0.3.0 
ruby-test 1.0.1 
sync-settings 0.8.1 
tabs-to-spaces 1.0.3 
toggle-quotes 1.0.1 
trailing-spaces 0.4.0 
```

**Comment by javaguirre** [comment]
Fixed on v0.6.1. Thank you!
